
CREATE TABLE migrations.employee_attendence_info
(
    day_description TEXT,
    is_attendent    BOOLEAN,
    emp_id          INTEGER NOT NULL,
    day             date    NOT NULL,
    CONSTRAINT pk_employee_attendence_info PRIMARY KEY (emp_id, day)
);

CREATE TABLE migrations.employees
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     TEXT                                     NOT NULL,
    salary        DOUBLE PRECISION,
    comany_number INTEGER,
    squad_number  INTEGER,
    track_code    INTEGER,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE migrations.out_source_companies
(
    comp_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comp_name   TEXT                                     NOT NULL,
    email       TEXT,
    CONSTRAINT pk_out_source_companies PRIMARY KEY (comp_number)
);

CREATE TABLE migrations.roles
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name TEXT                                     NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE migrations.squad
(
    squad_number    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    squad_name      TEXT,
    description     TEXT,
    scram_master_id INTEGER,
    tribe_id        INTEGER,
    CONSTRAINT pk_squad PRIMARY KEY (squad_number)
);

CREATE TABLE migrations.track
(
    track_code   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    track_name   TEXT                                     NOT NULL,
    description  TEXT,
    tech_lead_id INTEGER,
    CONSTRAINT pk_track PRIMARY KEY (track_code)
);

CREATE TABLE migrations.tribes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT,
    description TEXT,
    CONSTRAINT pk_tribes PRIMARY KEY (id)
);

CREATE TABLE migrations.users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name    TEXT,
    email        TEXT                                     NOT NULL,
    rid          INTEGER                                  NOT NULL,
    squad_number INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE migrations.employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_COMANY_NUMBER FOREIGN KEY (comany_number) REFERENCES migrations.out_source_companies (comp_number);

ALTER TABLE migrations.employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_SQUAD_NUMBER FOREIGN KEY (squad_number) REFERENCES migrations.squad (squad_number);

ALTER TABLE migrations.employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_TRACK_CODE FOREIGN KEY (track_code) REFERENCES migrations.track (track_code);

ALTER TABLE migrations.employee_attendence_info
    ADD CONSTRAINT FK_EMPLOYEE_ATTENDENCE_INFO_ON_EMP FOREIGN KEY (emp_id) REFERENCES migrations.employees (id);

ALTER TABLE migrations.squad
    ADD CONSTRAINT FK_SQUAD_ON_SCRAM_MASTER FOREIGN KEY (scram_master_id) REFERENCES migrations.users (id);

ALTER TABLE migrations.squad
    ADD CONSTRAINT FK_SQUAD_ON_TRIBE FOREIGN KEY (tribe_id) REFERENCES migrations.tribes (id);

ALTER TABLE migrations.track
    ADD CONSTRAINT FK_TRACK_ON_TECH_LEAD FOREIGN KEY (tech_lead_id) REFERENCES migrations.users (id);

ALTER TABLE migrations.users
    ADD CONSTRAINT FK_USERS_ON_RID FOREIGN KEY (rid) REFERENCES migrations.roles (id);

ALTER TABLE migrations.users
    ADD CONSTRAINT FK_USERS_ON_SQUAD_NUMBER FOREIGN KEY (squad_number) REFERENCES migrations.squad (squad_number);